In [92]:
print("hello")

hello

In [93]:
pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [94]:
import pandas as pd
import numpy as np

In [95]:
data={
    "name":["vishul","yash","swayam",None,"None","ram"],
    "age":[32,42,32,56,23,32],
    "rollno":[1,2,3,4,5,6]
}
df=pd.DataFrame(data)
df

     name  age  rollno
0  vishul   32       1
1    yash   42       2
2  swayam   32       3
3    None   56       4
4    None   23       5
5     ram   32       6

In [96]:
data=[
    ["vishul",32,1],
    ["yash",41,2]
]
df1=pd.DataFrame(data,columns=["Name","age",'rollno'])
df1

     Name  age  rollno
0  vishul   32       1
1    yash   41       2

In [97]:
s1=pd.Series([10,20,30,40])
s1

0    10
1    20
2    30
3    40
dtype: int64

In [98]:
df.head()

     name  age  rollno
0  vishul   32       1
1    yash   42       2
2  swayam   32       3
3    None   56       4
4    None   23       5

In [99]:
df.tail()

     name  age  rollno
1    yash   42       2
2  swayam   32       3
3    None   56       4
4    None   23       5
5     ram   32       6

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     6 non-null      int64
 2   rollno  6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [101]:
df.describe()

             age    rollno
count   6.000000  6.000000
mean   36.166667  3.500000
std    11.426577  1.870829
min    23.000000  1.000000
25%    32.000000  2.250000
50%    32.000000  3.500000
75%    39.500000  4.750000
max    56.000000  6.000000

In [102]:
df.infer_objects()

     name  age  rollno
0  vishul   32       1
1    yash   42       2
2  swayam   32       3
3    None   56       4
4    None   23       5
5     ram   32       6

In [103]:
df.dtypes

name      object
age        int64
rollno     int64
dtype: object

In [104]:
df.shape

(6, 3)

In [105]:
df.columns

Index(['name', 'age', 'rollno'], dtype='object')

In [106]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [107]:
df

     name  age  rollno
0  vishul   32       1
1    yash   42       2
2  swayam   32       3
3    None   56       4
4    None   23       5
5     ram   32       6

In [108]:
df.info()
df.describe()
df.index
df.shape
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     6 non-null      int64
 2   rollno  6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

name      object
age        int64
rollno     int64
dtype: object

In [109]:
df.describe()

             age    rollno
count   6.000000  6.000000
mean   36.166667  3.500000
std    11.426577  1.870829
min    23.000000  1.000000
25%    32.000000  2.250000
50%    32.000000  3.500000
75%    39.500000  4.750000
max    56.000000  6.000000

In [110]:
df.isna()

    name    age  rollno
0  False  False   False
1  False  False   False
2  False  False   False
3   True  False   False
4  False  False   False
5  False  False   False

In [111]:
df.isnull()

    name    age  rollno
0  False  False   False
1  False  False   False
2  False  False   False
3   True  False   False
4  False  False   False
5  False  False   False

In [112]:
df.isna().sum()

name      1
age       0
rollno    0
dtype: int64

In [113]:
df["bool"]=df["age"].apply(lambda x:True if x>30 else False)

In [114]:
df

     name  age  rollno   bool
0  vishul   32       1   True
1    yash   42       2   True
2  swayam   32       3   True
3    None   56       4   True
4    None   23       5  False
5     ram   32       6   True

In [115]:
df1["bool"]=df["age"]>30

In [116]:
df1

     Name  age  rollno  bool
0  vishul   32       1  True
1    yash   41       2  True

In [117]:
df1["none"]=[None,None]

In [118]:
df1

     Name  age  rollno  bool  none
0  vishul   32       1  True  None
1    yash   41       2  True  None

In [119]:
df

     name  age  rollno   bool
0  vishul   32       1   True
1    yash   42       2   True
2  swayam   32       3   True
3    None   56       4   True
4    None   23       5  False
5     ram   32       6   True

In [120]:
df.isnull().sum()

name      1
age       0
rollno    0
bool      0
dtype: int64

In [121]:
df.fillna("non null")

       name  age  rollno   bool
0    vishul   32       1   True
1      yash   42       2   True
2    swayam   32       3   True
3  non null   56       4   True
4      None   23       5  False
5       ram   32       6   True

In [122]:
df.fillna(df["age"].mode())

     name  age  rollno   bool
0  vishul   32       1   True
1    yash   42       2   True
2  swayam   32       3   True
3    None   56       4   True
4    None   23       5  False
5     ram   32       6   True

In [123]:
print(df["age"].mean())
print(df["age"].mode())
print(df["age"].median())

36.166666666666664
0    32
Name: age, dtype: int64
32.0

In [124]:
print(df["age"].mode())

0    32
Name: age, dtype: int64

In [125]:
df[df["age"]>32]

   name  age  rollno  bool
1  yash   42       2  True
3  None   56       4  True

In [126]:
df.fillna(0)

     name  age  rollno   bool
0  vishul   32       1   True
1    yash   42       2   True
2  swayam   32       3   True
3       0   56       4   True
4    None   23       5  False
5     ram   32       6   True

In [127]:
df.dropna()

     name  age  rollno   bool
0  vishul   32       1   True
1    yash   42       2   True
2  swayam   32       3   True
4    None   23       5  False
5     ram   32       6   True

In [128]:
df

     name  age  rollno   bool
0  vishul   32       1   True
1    yash   42       2   True
2  swayam   32       3   True
3    None   56       4   True
4    None   23       5  False
5     ram   32       6   True

In [129]:
df.drop_duplicates()

     name  age  rollno   bool
0  vishul   32       1   True
1    yash   42       2   True
2  swayam   32       3   True
3    None   56       4   True
4    None   23       5  False
5     ram   32       6   True

In [130]:
np.nan

nan

In [131]:
df["name"].replace("None",None)

0    vishul
1      yash
2    swayam
3      None
4      None
5       ram
Name: name, dtype: object

In [132]:
from  datetime import datetime
df["date"]=datetime.now().date()

In [133]:
df

     name  age  rollno   bool        date
0  vishul   32       1   True  2026-01-05
1    yash   42       2   True  2026-01-05
2  swayam   32       3   True  2026-01-05
3    None   56       4   True  2026-01-05
4    None   23       5  False  2026-01-05
5     ram   32       6   True  2026-01-05

In [134]:
df["date"]=df["date"]+pd.Timedelta(days=7)

In [135]:
df.dtypes

name      object
age        int64
rollno     int64
bool        bool
date      object
dtype: object

In [136]:
df

     name  age  rollno   bool        date
0  vishul   32       1   True  2026-01-12
1    yash   42       2   True  2026-01-12
2  swayam   32       3   True  2026-01-12
3    None   56       4   True  2026-01-12
4    None   23       5  False  2026-01-12
5     ram   32       6   True  2026-01-12

In [137]:
df["date"]=pd.to_datetime(df["date"])

In [138]:
df.dtypes

name              object
age                int64
rollno             int64
bool                bool
date      datetime64[ns]
dtype: object

In [139]:
df["date"]=df["date"]+pd.Timedelta(days=7)

In [140]:
df

     name  age  rollno   bool       date
0  vishul   32       1   True 2026-01-19
1    yash   42       2   True 2026-01-19
2  swayam   32       3   True 2026-01-19
3    None   56       4   True 2026-01-19
4    None   23       5  False 2026-01-19
5     ram   32       6   True 2026-01-19

In [141]:
df[["age","date"]]

   age       date
0   32 2026-01-19
1   42 2026-01-19
2   32 2026-01-19
3   56 2026-01-19
4   23 2026-01-19
5   32 2026-01-19

In [142]:
df[["date","age"]]

        date  age
0 2026-01-19   32
1 2026-01-19   42
2 2026-01-19   32
3 2026-01-19   56
4 2026-01-19   23
5 2026-01-19   32

In [143]:
df

     name  age  rollno   bool       date
0  vishul   32       1   True 2026-01-19
1    yash   42       2   True 2026-01-19
2  swayam   32       3   True 2026-01-19
3    None   56       4   True 2026-01-19
4    None   23       5  False 2026-01-19
5     ram   32       6   True 2026-01-19

In [144]:
df[(df["age"]>30) & (df["rollno"]>4)]

  name  age  rollno  bool       date
5  ram   32       6  True 2026-01-19

In [145]:
df.sort_values("age")

     name  age  rollno   bool       date
4    None   23       5  False 2026-01-19
0  vishul   32       1   True 2026-01-19
5     ram   32       6   True 2026-01-19
2  swayam   32       3   True 2026-01-19
1    yash   42       2   True 2026-01-19
3    None   56       4   True 2026-01-19

In [146]:
df.sort_values("age",ascending=False)

     name  age  rollno   bool       date
3    None   56       4   True 2026-01-19
1    yash   42       2   True 2026-01-19
0  vishul   32       1   True 2026-01-19
2  swayam   32       3   True 2026-01-19
5     ram   32       6   True 2026-01-19
4    None   23       5  False 2026-01-19

In [147]:
df[df["age"].rank() == 3.0]

     name  age  rollno  bool       date
0  vishul   32       1  True 2026-01-19
2  swayam   32       3  True 2026-01-19
5     ram   32       6  True 2026-01-19

In [148]:
df

     name  age  rollno   bool       date
0  vishul   32       1   True 2026-01-19
1    yash   42       2   True 2026-01-19
2  swayam   32       3   True 2026-01-19
3    None   56       4   True 2026-01-19
4    None   23       5  False 2026-01-19
5     ram   32       6   True 2026-01-19

In [149]:
# def fun():
#     yield from [1,2]
#     yield 3
# a=fun()
# next(a)
# next(a)
# next(a)

In [150]:
df

     name  age  rollno   bool       date
0  vishul   32       1   True 2026-01-19
1    yash   42       2   True 2026-01-19
2  swayam   32       3   True 2026-01-19
3    None   56       4   True 2026-01-19
4    None   23       5  False 2026-01-19
5     ram   32       6   True 2026-01-19

In [151]:
a=["5","1","10","3"]
print(sorted(a,key=len))

['5', '1', '3', '10']

In [152]:
y=(x for x in range(3))
print(y)

<generator object <genexpr> at 0x77a1aa2c9540>

In [153]:
next(y)

0

In [154]:
next(y)

1

In [155]:
y

In [156]:
list(y)

[2]

In [157]:
y=(x for x in range(3))
print(list(y))

[0, 1, 2]

In [158]:
bool([])

False

In [159]:
bool((([])))

False

In [160]:
bool([{}])

True

In [161]:
bool({()})

True

In [162]:
{} is {}

False

In [163]:
a=10
{a} is {a}

False

In [164]:
[a] is [a]

False

In [165]:
(a,) is (a,)

False

In [166]:
{a:1} is {a:1}

False

In [167]:
{a}=={a}

True

In [168]:
(a)==(a)

True

In [169]:
class A:
    def __init__(self,num):
        self.num=num
    P=a(10)
    def __getattr__("y",P):
        return 2

a = A(2)
print(a.x)
print(a.y)

SyntaxError: invalid syntax (4156900961.py, line 5)

In [ ]:
lis=[*(1,2,3,45,5),5]
lis

[1, 2, 3, 45, 5, 5]

In [ ]:
se={*(1,2,3,45,5),5}
se

{1, 2, 3, 5, 45}

In [ ]:
def chain():
    yield from range(3)
    yield from [10, 20]
a=chain()

In [ ]:
print(next(a))
list(a)

0

[1, 2, 10, 20]

In [ ]:
list(chain())

[0, 1, 2, 10, 20]

In [ ]:
a=["1","20","3"]
# a.sort(key=int)

In [ ]:
a

['1', '20', '3']

In [ ]:
b=sorted((1,"10b","5a"),key=str)

In [ ]:
b

[1, '10b', '5a']

In [ ]:
def gen():
    x = yield
    y= yield
    yield x * 2

g = gen()
next(g)       
# next(g)    
# print(g.send(10))

In [ ]:
print(g.send(30))

None

In [ ]:
print(g.send(20))

60

In [ ]:
a=(1,2,3)
print(id(list(a)) ,id(list(a)),sep="\t")

131536231010496	131536231007808

In [ ]:
list(a) is list(a)

False

In [ ]:
() is ()

<>:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
/tmp/ipykernel_31773/4109779674.py:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  () is ()

True

In [ ]:
{} is {}

False

In [ ]:
[] is []

False

In [ ]:
bool({0})

True

In [ ]:
import random

it = iter(lambda: random.randint(1, 5), 3)

for x in it:
    print(x)

4
5
2
1

In [ ]:
a=list(list[(1,2,set([3,4]))])
b=a+[1,2,3]
tuple(b)

(*list[1, 2, {3, 4}], 1, 2, 3)

In [ ]:
a=list([1,2,set([3,2]),4])
a

[1, 2, {2, 3}, 4]

In [ ]:
bool(None)

False

In [ ]:
bool([None])

True

In [ ]:
bool((None))

False

In [ ]:
bool({None})

True

In [ ]:
bool(((None,)))

True

In [ ]:
for i in {None}:
    print(i)

None

In [ ]:
for i in None,None:
    print(i)

None
None

In [ ]:
all([0, "", 1])  # True

False

In [ ]:
a=(lambda y,x:[20,60])
# next(a(20 ,23))
a(20,10)

[20, 60]

In [ ]:
type(a)

function

In [ ]:
any({"",None})

False

In [ ]:
any({})

False

In [ ]:
all({})

True

In [ ]:
class a:
    def __str__(self):
        return "str"
    def __repr__(self):
        return "repr"
    
b=a()
print(b)
b

str

repr

In [ ]:
class demo:
    def __init__(self):
        self.x = 10   # calls __setattr__

    #Called for EVERY attribute access
    def __getattribute__(self, name):
        print(f"__getattribute__ called for: {name}")
        return object.__getattribute__(self, name)

    #Called ONLY if attribute NOT found
    def __getattr__(self, name):
        print(f"__getattr__ called for missing: {name}")
        return "default"

    #Called on attribute assignment
    def __setattr__(self, name, value):
        print(f"__setattr__ called: {name} = {value}")
        object.__setattr__(self, name, value)

    # Called on attribute deletion
    def __delattr__(self, name):
        print(f"__delattr__ called for: {name}")
        object.__delattr__(self, name)

In [ ]:
d=demo()

__setattr__ called: x = 10

In [ ]:
d.x

__getattribute__ called for: x

10

In [ ]:
d.x=20

__setattr__ called: x = 20

In [ ]:
d.x

__getattribute__ called for: x

20

In [ ]:
d.j

__getattribute__ called for: j
__getattr__ called for missing: j

'default'

In [ ]:
d.j=20

__setattr__ called: j = 20

In [ ]:
d.j

__getattribute__ called for: j

20

In [ ]:
d.k

__getattribute__ called for: k
__getattr__ called for missing: k

'default'

In [ ]:
d.k=30

__setattr__ called: k = 30

In [ ]:
d.i,d.k,d.j

__getattribute__ called for: i
__getattr__ called for missing: i
__getattribute__ called for: k
__getattribute__ called for: j

('default', 30, 20)

In [ ]:
class MyList:
    def __init__(self):
        self.data = {}

    # obj[key]
    def __getitem__(self, key):
        print(f"__getitem__ called with key: {key}")
        return self.data[key]

    # obj[key] = value
    def __setitem__(self, key, value):
        print(f"__setitem__ called: {key} = {value}")
        self.data[key] = value

    # del obj[key]
    def __delitem__(self, key):
        print(f"__delitem__ called for key: {key}")
        del self.data[key]

    # item in obj
    def __contains__(self, item):
        print(f"__contains__ called for item: {item}")
        return item in self.data.values()

In [ ]:
obj=MyList()

In [ ]:
obj

In [ ]:
obj["a"]=100

__setitem__ called: a = 100

In [ ]:
obj["b"]=200

__setitem__ called: b = 200

In [ ]:
200 in obj

__contains__ called for item: 200

True

In [ ]:
obj["a"]

__getitem__ called with key: a

100

In [ ]:
x=[i for i in range(3)]

In [ ]:
x

[0, 1, 2]

In [ ]:
x=(x for x in range(3))

In [ ]:
x

In [ ]:
list(x)

[0, 1, 2]

In [ ]:
n = 10
try:
    res = n 
    raise ValueError("no error")
except ValueError as e:
    print(e)

no error

In [ ]:
a=["a","b","c"]
print(enumerate(a))

<enumerate object at 0x77a1aa3bbbf0>

In [ ]:
list(enumerate(a))

[(0, 'a'), (1, 'b'), (2, 'c')]

In [ ]:
zip(a)

In [ ]:
list(zip(a))

[('a',), ('b',), ('c',)]

In [ ]:
a=[10,20,30,[40,50]]

In [ ]:
b=a

In [ ]:
b.append(60)

In [ ]:
a

[10, 20, 30, [40, 50], 60]

In [ ]:
b.remove(10)

In [ ]:
b

[20, 30, [40, 50], 60]

In [ ]:
a

[20, 30, [40, 50], 60]

In [ ]:
# try:
#     x = 10 / 0
# except ZeroDivisionError:
#     print("Logging error")
#     raise

In [ ]:
from abc import ABC, abstractmethod

class Vehicle(ABC):

    @abstractmethod
    def start(self):
        pass

class Car(Vehicle):
    def start(self):
        print("Car starts with a key")

class Bike(Vehicle):
    def start(self):
        print("Bike starts with a button")

In [ ]:
# a=Vehicle()

In [ ]:
with open("dum.txt","w+") as f:
    print(f.read())
    print(f.tell())
    print(f.seek(10))
    f.write("hi i am writting")
    print(f.read())

0
10

In [170]:
df

     name  age  rollno   bool       date
0  vishul   32       1   True 2026-01-19
1    yash   42       2   True 2026-01-19
2  swayam   32       3   True 2026-01-19
3    None   56       4   True 2026-01-19
4    None   23       5  False 2026-01-19
5     ram   32       6   True 2026-01-19

In [173]:
df.isnull().sum()

name      1
age       0
rollno    0
bool      0
date      0
dtype: int64

In [178]:
print(df.replace("None","roy",inplace=True))

None

In [179]:
df

     name  age  rollno   bool       date
0  vishul   32       1   True 2026-01-19
1    yash   42       2   True 2026-01-19
2  swayam   32       3   True 2026-01-19
3    None   56       4   True 2026-01-19
4     roy   23       5  False 2026-01-19
5     ram   32       6   True 2026-01-19

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     6 non-null      int64
 2   rollno  6 non-null      int64
 3   bool    6 non-null      bool
 4   date    6 non-null      datetime64[ns]
dtypes: bool(1), datetime64[ns](1), int64(2), object(1)
memory usage: 330.0+ bytes

In [182]:
df[df["age"]>40]

   name  age  rollno  bool       date
1  yash   42       2  True 2026-01-19
3  None   56       4  True 2026-01-19

In [183]:
df["mark1"]=[98,88,67,86,84,74]

In [184]:
df

     name  age  rollno   bool       date  mark1
0  vishul   32       1   True 2026-01-19     98
1    yash   42       2   True 2026-01-19     88
2  swayam   32       3   True 2026-01-19     67
3    None   56       4   True 2026-01-19     86
4     roy   23       5  False 2026-01-19     84
5     ram   32       6   True 2026-01-19     74

In [186]:
df["mark2"]=[87,98,54,78,96,84]

In [188]:
df

     name  age  rollno   bool       date  mark1  mark2
0  vishul   32       1   True 2026-01-19     98     87
1    yash   42       2   True 2026-01-19     88     98
2  swayam   32       3   True 2026-01-19     67     54
3    None   56       4   True 2026-01-19     86     78
4     roy   23       5  False 2026-01-19     84     96
5     ram   32       6   True 2026-01-19     74     84

In [189]:
df["total"]=df["mark1"]+df["mark2"]

In [190]:
df

     name  age  rollno   bool       date  mark1  mark2  total
0  vishul   32       1   True 2026-01-19     98     87    185
1    yash   42       2   True 2026-01-19     88     98    186
2  swayam   32       3   True 2026-01-19     67     54    121
3    None   56       4   True 2026-01-19     86     78    164
4     roy   23       5  False 2026-01-19     84     96    180
5     ram   32       6   True 2026-01-19     74     84    158

In [196]:
df.rename(columns={"mark1":"marks1"},inplace=True)

In [202]:
df.rename(columns={"mark2":"marks2"},inplace=True)

In [200]:
df

     name  age  rollno   bool       date  marks1  marks2  total
0  vishul   32       1   True 2026-01-19      98      87    185
1    yash   42       2   True 2026-01-19      88      98    186
2  swayam   32       3   True 2026-01-19      67      54    121
3    None   56       4   True 2026-01-19      86      78    164
4     roy   23       5  False 2026-01-19      84      96    180
5     ram   32       6   True 2026-01-19      74      84    158

In [204]:
df["result"]=df["total"].apply(lambda x:"Pass" if x>160 else "Fail")

In [205]:
df

     name  age  rollno   bool       date  marks1  marks2  total result
0  vishul   32       1   True 2026-01-19      98      87    185   Pass
1    yash   42       2   True 2026-01-19      88      98    186   Pass
2  swayam   32       3   True 2026-01-19      67      54    121   Fail
3    None   56       4   True 2026-01-19      86      78    164   Pass
4     roy   23       5  False 2026-01-19      84      96    180   Pass
5     ram   32       6   True 2026-01-19      74      84    158   Fail

In [213]:
df["marks2"].replace(54,84,inplace=True)
df["marks1"].replace(67,94,inplace=True)

/tmp/ipykernel_41340/766757154.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks2"].replace(54,84,inplace=True)
/tmp/ipykernel_41340/766757154.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks1"].replace(67,94,inplace=True)

In [214]:
df["total"]=df["marks2"]+df["marks1"]

In [215]:
df

     name  age  rollno   bool       date  marks1  marks2  total result
0  vishul   32       1   True 2026-01-19      98      87    185   Pass
1    yash   42       2   True 2026-01-19      88      98    186   Pass
2  swayam   32       3   True 2026-01-19      94      84    178   Fail
3    None   56       4   True 2026-01-19      86      78    164   Pass
4     roy   23       5  False 2026-01-19      84      96    180   Pass
5     ram   32       6   True 2026-01-19      74      84    158   Fail

In [216]:
df["result"]=df["total"].apply(lambda x:"Pass" if x>160 else "Fail")

In [217]:
df

     name  age  rollno   bool       date  marks1  marks2  total result
0  vishul   32       1   True 2026-01-19      98      87    185   Pass
1    yash   42       2   True 2026-01-19      88      98    186   Pass
2  swayam   32       3   True 2026-01-19      94      84    178   Pass
3    None   56       4   True 2026-01-19      86      78    164   Pass
4     roy   23       5  False 2026-01-19      84      96    180   Pass
5     ram   32       6   True 2026-01-19      74      84    158   Fail

In [218]:
df["dept"]=["AI","AI","python","react","react","web development"]

In [219]:
df

,name,age,rollno,bool,date,marks1,marks2,total,result,dept
0,vishul,32,1,True,2026-01-19,98,87,185,Pass,AI
1,yash,42,2,True,2026-01-19,88,98,186,Pass,AI
2,swayam,32,3,True,2026-01-19,94,84,178,Pass,python
3,None,56,4,True,2026-01-19,86,78,164,Pass,react
4,roy,23,5,False,2026-01-19,84,96,180,Pass,react
5,ram,32,6,True,2026-01-19,74,84,158,Fail,web development

In [234]:
df.loc[df.groupby("dept")["total"].idxmax(),["name","dept","total"]]

     name             dept  total
1    yash               AI    186
2  swayam           python    178
4     roy            react    180
5     ram  web development    158

In [235]:
df.groupby("age")["total"].max()

age
23    180
32    185
42    186
56    164
Name: total, dtype: int64

In [236]:
df.loc[df.groupby("age")["total"].idxmax()]

     name  age  rollno   bool       date  marks1  marks2  total result   dept
4     roy   23       5  False 2026-01-19      84      96    180   Pass  react
0  vishul   32       1   True 2026-01-19      98      87    185   Pass     AI
1    yash   42       2   True 2026-01-19      88      98    186   Pass     AI
3    None   56       4   True 2026-01-19      86      78    164   Pass  react

In [239]:
df.groupby("dept")["total"].agg(["sum","max","mean"])

                 sum  max   mean
dept
AI               371  186  185.5
python           178  178  178.0
react            344  180  172.0
web development  158  158  158.0

In [241]:
df.groupby("dept")["total"].agg([sum,max,"mean"])

/tmp/ipykernel_41340/3204885913.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby("dept")["total"].agg([sum,max,"mean"])
/tmp/ipykernel_41340/3204885913.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby("dept")["total"].agg([sum,max,"mean"])

                 sum  max   mean
dept
AI               371  186  185.5
python           178  178  178.0
react            344  180  172.0
web development  158  158  158.0

In [246]:
df1.rename(columns={"Name":"name"},inplace=True)

In [251]:
pd.merge(df,df1,on="name",how="outer")

,name,age_x,rollno_x,bool_x,date,marks1,marks2,total,result,dept,age_y,rollno_y,bool_y,none
0,ram,32,6,True,2026-01-19,74,84,158,Fail,web development,NaN,NaN,NaN,NaN
1,roy,23,5,False,2026-01-19,84,96,180,Pass,react,NaN,NaN,NaN,NaN
2,swayam,32,3,True,2026-01-19,94,84,178,Pass,python,NaN,NaN,NaN,NaN
3,vishul,32,1,True,2026-01-19,98,87,185,Pass,AI,32.0,1.0,True,None
4,yash,42,2,True,2026-01-19,88,98,186,Pass,AI,41.0,2.0,True,None
5,None,56,4,True,2026-01-19,86,78,164,Pass,react,NaN,NaN,NaN,NaN