In [1]:
In [1]: import numpy as np

In [2]: import pandas as pd

In [2]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

In [3]:
s

a   -0.607906
b    0.730681
c   -0.298566
d   -0.139755
e    1.283911
dtype: float64

In [4]:
s.iloc[0]

np.float64(-0.6079058392001242)

In [5]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0,5.0], index=["a", "b", "c","e"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [6]:
# d = {
#     "one": pd.Series([1.0, 2.0, 3.0,5.0]),
#     "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
# }

In [7]:
df = pd.DataFrame(d)

In [8]:
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
e  5.0  NaN

In [9]:
pd.DataFrame(d, index=["d", "b", "a"])

   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [10]:
pd.DataFrame(d, index=["d", "b", "a"], columns=["two", "three"])

   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

In [11]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [12]:
d = {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]}

In [13]:
pd.DataFrame(d)

   one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [15]:
pd.DataFrame(d, index=["a", "b", "c", "d"])

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

In [24]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=["a", " b", "c", "d"],
)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

In [25]:
frames = [df1, df2, df3]

result = pd.concat(frames)

result

      A    B    C    D
a    A0   B0   C0   D0
 b   A1   B1   C1   D1
c    A2   B2   C2   D2
d    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [21]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[2, 3, 6, 7],
)


result = pd.concat([df1, df4], axis=1)

result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [26]:
pd.concat([df1, df4], ignore_index=True, sort=False)

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [27]:
df1

     A   B   C   D
a   A0  B0  C0  D0
 b  A1  B1  C1  D1
c   A2  B2  C2  D2
d   A3  B3  C3  D3

In [31]:
left = pd.DataFrame(
    {"k": ["K0", "K1", "K1", "K2"], "lv": [1, 2, 3, 4], "s": ["a", "b", "c", "d"]}
)


right = pd.DataFrame({"k": ["K1", "K2", "K4"], "rv": [1, 2, 3]})

pd.merge_ordered(left, right, fill_method="ffill", left_by="s")

     k   lv  s   rv
0   K0  1.0  a  NaN
1   K1  1.0  a  1.0
2   K2  1.0  a  2.0
3   K4  1.0  a  3.0
4   K1  2.0  b  1.0
5   K2  2.0  b  2.0
6   K4  2.0  b  3.0
7   K1  3.0  c  1.0
8   K2  3.0  c  2.0
9   K4  3.0  c  3.0
10  K1  NaN  d  1.0
11  K2  4.0  d  2.0
12  K4  4.0  d  3.0

In [44]:
arr = [0,2,3.7,4,6,7,12]

factor = pd.cut(arr, 4)

factor

[(-0.012, 3.0], (-0.012, 3.0], (3.0, 6.0], (3.0, 6.0], (3.0, 6.0], (6.0, 9.0], (9.0, 12.0]]
Categories (4, interval[float64, right]): [(-0.012, 3.0] < (3.0, 6.0] < (6.0, 9.0] < (9.0, 12.0]]